name: temoa-stoch-py2
channels:
    - defaults
    - conda-forge
dependencies:
    - python=2.7
    - pathlib=1.0.1
    - xlwt=1.3.0
    - ipython=5.8.0
    - matplotlib=2.2.3
    - pandas=0.24.2
    - numpy=1.16.6
    - scipy=1.2.1
    - joblib=0.14.1
    - salib
    - pydoe=0.3.8
    - pyutilib=5.7.2
    - glpk=4.65
    - xlrd=1.2.0
